#!/bin/sh

# Firewall-Regel hinzufügen: Allow IGMP Broadcast
uci add firewall rule
uci set firewall.@rule[-1].name='Allow-IGMP-Broadcast'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].proto='udp'
uci set firewall.@rule[-1].dest_ip='224.0.0.0/4'
uci set firewall.@rule[-1].target='ACCEPT'

# Änderungen speichern
uci commit firewall

exit 0
