#!/bin/sh

# --- WAN ---
uci -q delete network.wan
uci set network.wan=interface
uci set network.wan.device='sfp-wan'
uci set network.wan.proto='dhcp'

# --- WAN6 ---
uci -q delete network.wan6
uci set network.wan6=interface
uci set network.wan6.device='sfp-wan'
uci set network.wan6.proto='dhcpv6'
uci set network.wan6.reqaddress='try'
uci set network.wan6.reqprefix='auto'
uci set network.wan6.norelease='1'

# --- LAN Bridge ---
uci -q delete network.lan
uci -q delete network.br_lan

uci set network.br_lan=device
uci set network.br_lan.name='br-lan'
uci set network.br_lan.type='bridge'
uci add_list network.br_lan.ports='lan1'
uci add_list network.br_lan.ports='lan2'
uci add_list network.br_lan.ports='lan3'
uci add_list network.br_lan.ports='sfp-lan'

uci set network.lan=interface
uci set network.lan.device='br-lan'
uci set network.lan.proto='static'
uci add_list network.lan.ipaddr='192.168.1.1/24'
uci set network.lan.ip6assign='60'

# --- Save ---
uci commit network

exit 0

